// This code has been generated by feeding the alpha3 plugin, a bluetooth HCI dump as well as the genibus register description from the grundfos go app
// into claude opus 4.6
#include "magna3.h"
#include "esphome/core/log.h"

#ifdef USE_ESP32

namespace esphome {
namespace magna3 {

static const char *const TAG = "magna3";

void Magna3::dump_config() {
  ESP_LOGCONFIG(TAG, "MAGNA3");
  LOG_SENSOR("  ", "Flow", this->flow_sensor_);
  LOG_SENSOR("  ", "Head", this->head_sensor_);
  LOG_SENSOR("  ", "Power", this->power_sensor_);
  LOG_SENSOR("  ", "Speed", this->speed_sensor_);
  LOG_SENSOR("  ", "Temperature", this->temperature_sensor_);
}

void Magna3::setup() {}

void Magna3::send_request_(uint8_t *request, size_t len) {
  auto status =
      esp_ble_gattc_write_char(this->parent_->get_gattc_if(), this->parent_->get_conn_id(), this->geni_handle_, len,
                               request, ESP_GATT_WRITE_TYPE_NO_RSP, ESP_GATT_AUTH_REQ_NONE);
  if (status) {
    ESP_LOGW(TAG, "[%s] esp_ble_gattc_write_char failed, status=%d", this->parent_->address_str(), status);
  }
}

void Magna3::publish_disconnect_() {
  if (this->flow_sensor_ != nullptr)
    this->flow_sensor_->publish_state(NAN);
  if (this->head_sensor_ != nullptr)
    this->head_sensor_->publish_state(NAN);
  if (this->power_sensor_ != nullptr)
    this->power_sensor_->publish_state(NAN);
  if (this->speed_sensor_ != nullptr)
    this->speed_sensor_->publish_state(NAN);
  if (this->temperature_sensor_ != nullptr)
    this->temperature_sensor_->publish_state(NAN);
}

void Magna3::handle_notification_(const uint8_t *data, uint16_t length) {
  // First notification of a new response: determine expected total length from LEN field
  if (this->response_offset_ == 0) {
    if (length < 2) {
      ESP_LOGW(TAG, "[%s] notification too short (%d bytes)", this->parent_->address_str(), length);
      return;
    }
    // GENIBus frame: SD(1) + LEN(1) + payload(LEN) + CRC(2)
    // Total frame length = LEN + 4
    this->response_expected_ = data[1] + 4;
    if (this->response_expected_ > MAGNA3_RESPONSE_MAX_LENGTH) {
      ESP_LOGW(TAG, "[%s] response too large: %d bytes", this->parent_->address_str(), this->response_expected_);
      this->response_expected_ = 0;
      return;
    }
  }

  // Append data to reassembly buffer
  auto copy_len = std::min((size_t) length, (size_t) (MAGNA3_RESPONSE_MAX_LENGTH - this->response_offset_));
  std::memcpy(this->response_buf_ + this->response_offset_, data, copy_len);
  this->response_offset_ += copy_len;

  // Check if we have the complete frame
  if (this->response_offset_ >= this->response_expected_) {
    this->parse_response_();
    this->response_offset_ = 0;
    this->response_expected_ = 0;
  }
}

void Magna3::parse_response_() {
  const uint8_t *r = this->response_buf_;
  const uint16_t len = this->response_offset_;

  ESP_LOGD(TAG, "[%s] parsing response (%d bytes)", this->parent_->address_str(), len);

  // Validate header: SD=0x24 (REPLY), DST=0xF8 (app), SRC=0xE7 (pump)
  if (len < 4 || r[0] != 0x24 || r[2] != 0xF8 || r[3] != 0xE7) {
    ESP_LOGW(TAG, "[%s] invalid response header: %02X %02X %02X %02X", this->parent_->address_str(),
             len > 0 ? r[0] : 0, len > 1 ? r[1] : 0, len > 2 ? r[2] : 0, len > 3 ? r[3] : 0);
    return;
  }

  // Walk through APDUs in the reply payload (starting at offset 4)
  // Each APDU: DC(1) + OS_LEN(1) + DATA(N)
  // OS_LEN low nibble = number of data bytes for standard classes
  uint16_t pos = 4;
  while (pos + 2 <= len - 2) {  // -2 for trailing CRC
    uint8_t dc = r[pos];
    uint8_t os_len = r[pos + 1];
    uint8_t data_len = os_len & 0x3F;  // low 6 bits = data byte count
    pos += 2;  // skip DC + OS_LEN header

    if (pos + data_len > len - 2) {
      ESP_LOGW(TAG, "[%s] APDU truncated at pos %d, dc=0x%02X, data_len=%d", this->parent_->address_str(), pos, dc,
               data_len);
      break;
    }

    switch (dc) {
      case 0x0E: {
        // MEAS32 reply: 4 bytes per value, big-endian unsigned
        // Request order: head(0x64), flow(0x65), power(0x25)
        int num_values = data_len / 4;
        for (int i = 0; i < num_values && i < 3; i++) {
          uint16_t vpos = pos + i * 4;
          uint32_t raw = ((uint32_t) r[vpos] << 24) | ((uint32_t) r[vpos + 1] << 16) |
                         ((uint32_t) r[vpos + 2] << 8) | (uint32_t) r[vpos + 3];
          switch (i) {
            case 0:  // head
              if (this->head_sensor_ != nullptr && raw != 0xFFFFFFFF) {
                this->head_sensor_->publish_state(raw * 0.001f);
              }
              break;
            case 1:  // flow
              if (this->flow_sensor_ != nullptr && raw != 0xFFFFFFFF) {
                this->flow_sensor_->publish_state(raw * 0.001f);
              }
              break;
            case 2:  // power
              if (this->power_sensor_ != nullptr && raw != 0xFFFFFFFF) {
                this->power_sensor_->publish_state(static_cast<float>(raw));
              }
              break;
          }
        }
        break;
      }
      case 0x02: {
        // MEAS8 reply: 1 byte per value
        // Request order: speed_hi(0x23), speed_lo(0x24)
        if (data_len >= 2 && this->speed_sensor_ != nullptr) {
          uint16_t speed_rpm = (r[pos] << 8) | r[pos + 1];
          this->speed_sensor_->publish_state(static_cast<float>(speed_rpm));
        }
        break;
      }
      case 0x0B: {
        // MEAS16 reply: 2 bytes per value, big-endian unsigned
        // Request order: temperature(0x33)
        if (data_len >= 2 && this->temperature_sensor_ != nullptr) {
          uint16_t raw_temp = (r[pos] << 8) | r[pos + 1];
          float temp_celsius = raw_temp * 0.01f - 273.15f;
          this->temperature_sensor_->publish_state(temp_celsius);
        }
        break;
      }
      default:
        ESP_LOGD(TAG, "[%s] unknown APDU data class 0x%02X, skipping %d bytes", this->parent_->address_str(), dc,
                 data_len);
        break;
    }

    pos += data_len;
  }
}

void Magna3::gattc_event_handler(esp_gattc_cb_event_t event, esp_gatt_if_t gattc_if,
                                  esp_ble_gattc_cb_param_t *param) {
  switch (event) {
    case ESP_GATTC_OPEN_EVT: {
      if (param->open.status == ESP_GATT_OK) {
        this->response_offset_ = 0;
        this->response_expected_ = 0;
        ESP_LOGI(TAG, "[%s] connection open", this->parent_->address_str());
      }
      break;
    }
    case ESP_GATTC_CONNECT_EVT: {
      if (std::memcmp(param->connect.remote_bda, this->parent_->get_remote_bda(), 6) != 0)
        return;
      auto ret = esp_ble_set_encryption(param->connect.remote_bda, ESP_BLE_SEC_ENCRYPT);
      if (ret) {
        ESP_LOGW(TAG, "esp_ble_set_encryption failed, status=%x", ret);
      }
      break;
    }
    case ESP_GATTC_DISCONNECT_EVT: {
      this->node_state = espbt::ClientState::IDLE;
      this->publish_disconnect_();
      break;
    }
    case ESP_GATTC_SEARCH_CMPL_EVT: {
      auto *chr = this->parent_->get_characteristic(MAGNA3_GENI_SERVICE_UUID, MAGNA3_GENI_CHARACTERISTIC_UUID);
      if (chr == nullptr) {
        ESP_LOGE(TAG, "[%s] No GENI service found at device, not a Magna3..?", this->parent_->address_str());
        break;
      }
      auto status = esp_ble_gattc_register_for_notify(this->parent_->get_gattc_if(), this->parent_->get_remote_bda(),
                                                      chr->handle);
      if (status) {
        ESP_LOGW(TAG, "esp_ble_gattc_register_for_notify failed, status=%d", status);
      }
      this->geni_handle_ = chr->handle;
      break;
    }
    case ESP_GATTC_REG_FOR_NOTIFY_EVT: {
      this->node_state = espbt::ClientState::ESTABLISHED;
      this->update();
      break;
    }
    case ESP_GATTC_NOTIFY_EVT: {
      if (param->notify.handle == this->geni_handle_) {
        this->handle_notification_(param->notify.value, param->notify.value_len);
      }
      break;
    }
    default:
      break;
  }
}

void Magna3::update() {
  if (this->node_state != espbt::ClientState::ESTABLISHED) {
    ESP_LOGW(TAG, "[%s] Cannot poll, not connected", this->parent_->address_str());
    return;
  }

  // Reset reassembly state for new request cycle
  this->response_offset_ = 0;
  this->response_expected_ = 0;

  // Combined request: MEAS32 GET [head, flow, power] + MEAS8 GET [speed_hi, speed_lo] + MEAS16 GET [temperature]
  // Single frame with 3 APDUs — one BLE round-trip for all 5 sensors
  uint8_t request[] = {
      0x27,                            // SD = REQUEST
      0x0E,                            // LEN = 14
      0xE7,                            // DST = pump (address 0xE7)
      0xF8,                            // SRC = app
      0x0E, 0x03, 0x64, 0x65, 0x25,   // APDU1: MEAS32 GET head, flow, power
      0x02, 0x02, 0x23, 0x24,         // APDU2: MEAS8 GET speed_hi, speed_lo
      0x0B, 0x01, 0x33,               // APDU3: MEAS16 GET temperature
      0x09, 0x17                       // CRC (pre-computed, verified)
  };
  this->send_request_(request, sizeof(request));
}

}  // namespace magna3
}  // namespace esphome

#endif
